# Spring Boot Config
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        # JPA Query Console
        show_sql: false

        # SQL Format
        format_sql: true
        ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect

# Print Bind Parameter
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace